from pathlib import Path

def build_markdown_report(records):
    """Bangun tabel Markdown dari data rekap mahasiswa."""
    lines = [
        "# Rekap Nilai Mahasiswa",
        "",
        "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |",
        "|---|---|---:|---:|:---:|"
    ]
    for r in records:
        lines.append(
            f"| {r['nim']} | {r['nama']} | {r['hadir']:.2f} | {r['akhir']:.2f} | {r['predikat']} |"
        )
    lines.append("")
    lines.append("Generated by student_performance_tracker")
    return "\n".join(lines)

def save_text(path, content):
    """Simpan teks ke file Markdown."""
    Path(path).write_text(content, encoding="utf-8")
 
